#!/bin/bash
# Generate list of all available KFLAT tests and output it
# as C compatible array

HEADER=$(cat <<-END
/**
 * @file tests_list.h
 * @author Samsung R&D Poland - Mobile Security Group
 * @brief Header file collecting the list of all available KFLAT tests
 *  This file has been auto-generated by tests_list_gen script
 */
#include "common.h"

/*
 * Extern-declaration for all test case structures
 */
END
)

MIDDLE=$(cat <<-END

/*
 * Array storing the list of all available test cases
 */
const struct kflat_test_case* test_cases[] = {
END
)

FOOTER=$(cat <<-END
};
END
)

pushd $M/tests > /dev/null
EXTERNS=`grep -oP 'KFLAT_REGISTER_TEST\(".+", [^,]+' *.c | grep -oP ',\s*.*' | grep -oP '[^\s,]+' | awk '{print "test_case_" $0}' | awk '{print "extern struct kflat_test_case " $0 ";"}'`
ENTRIES=`grep -oP 'KFLAT_REGISTER_TEST\(".+", [^,]+' *.c | grep -oP ',\s*.*' | grep -oP '[^\s,]+' | awk '{print "test_case_" $0}' | awk '{print "\t&" $0 ","}'`

EXTERNS+=`grep -oP 'KFLAT_REGISTER_TEST_GFA\(".+", [^,]+' *.c | grep -oP ',\s*.*' | grep -oP '[^\s,]+' | awk '{print "test_case_" $0}' | awk '{print "extern struct kflat_test_case " $0 ";"}'`
ENTRIES+=`grep -oP 'KFLAT_REGISTER_TEST_GFA\(".+", [^,]+' *.c | grep -oP ',\s*.*' | grep -oP '[^\s,]+' | awk '{print "test_case_" $0}' | awk '{print "\t&" $0 ","}'`


echo "$HEADER" > tests_list.h
echo "$EXTERNS" >> tests_list.h
echo "$MIDDLE" >> tests_list.h
echo "$ENTRIES" >> tests_list.h
echo "$FOOTER" >> tests_list.h

popd > /dev/null
