# Samsung R&D Poland - Mobile Security Group

TOPDIR := ${M}/../
ccflags-y := -std=gnu99 -Wno-unused-local-typedefs -I${TOPDIR}/include/ $(patsubst %,-D%,$(KFLAT_OPTS)) -DFLATTEN_KERNEL_BSP

LINUX_INCLUDES := ${LINUX_INCLUDES} ${TOPDIR}/include/

# Generate list of available kflat tests
quiet_cmd_kflat_tests_gen = GEN     $@
cmd_kflat_tests_gen = $< $@

$(obj)/tests/tests_list.h: $(obj)/tests/tests_list_gen.sh
	$(call cmd,kflat_tests_gen)

$(obj)/kflat.o: $(obj)/tests/tests_list.h

# Build kflat core module
kflat_core-y = kflat.o kflat_impl.o probing.o kdump.o flatten_impl.o
kflat_core-$(CONFIG_ARM64) += probing_arm.o
kflat_core-$(CONFIG_X86_64) += probing_x86.o

# Build kflat tests
ccflags-y += -I${TOPDIR}/tests -D__TESTER__

common_test_files = $(wildcard $(src)/tests/*.c)
common_filenames = $(notdir $(common_test_files))
kflat_test_files = $(wildcard $(src)/tests/kflat/*.c)
kflat_filenames = $(notdir $(kflat_test_files))
out_files = $(addprefix tests/, $(common_filenames:.c=.o))
out_files += $(addprefix tests/kflat/, $(kflat_filenames:.c=.o))
kflat_core-y += $(out_files)

# Create .ko file
obj-m := kflat_core.o
