KBUILD_EXTRA_SYMBOLS=/home/j.pilimon2/kflat/build/core/Module.symvers

KCOV_INSTRUMENT	:= n
KASAN_SANITIZE 	:= n

ccflags-y := -Wno-undefined-internal -Wno-visibility -Wno-gcc-compat -Wno-unused-variable -I$PWD/ -I/home/j.pilimon2/kflat/include/

do_init_module-objs := do_init_module_recipe.o
obj-m += do_init_module.o


