/**
 * @file kflat_compatibility.h
 * @author Pawel Wieczorek (p.wieczorek@samsung.com)
 * @brief This header files stores wrappers for older KFLAT macros. Avoid using
 *      them in newer recipes, as they might be eventually removed in the future
 * 
 */

/***************************
 * FUNCTION_*_ITER wrappers
 ***************************/
#define FUNCTION_DEFINE_FLATTEN_STRUCT_ARRAY_ITER(FLTYPE) \
	FUNCTION_DEFINE_FLATTEN_STRUCT_ARRAY(FLTYPE)

#define FUNCTION_DECLARE_FLATTEN_STRUCT_ARRAY_ITER(FLTYPE) \
	FUNCTION_DECLARE_FLATTEN_STRUCT_ARRAY(FLTYPE)

#define FUNCTION_DEFINE_FLATTEN_STRUCT_TYPE_ARRAY_ITER(FLTYPE) \
	FUNCTION_DEFINE_FLATTEN_STRUCT_TYPE_ARRAY(FLTYPE)

#define FUNCTION_DECLARE_FLATTEN_STRUCT_TYPE_ARRAY_ITER(FLTYPE) \
	FUNCTION_DECLARE_FLATTEN_STRUCT_TYPE_ARRAY(FLTYPE)

#define FUNCTION_DEFINE_FLATTEN_STRUCT_ARRAY_ITER_SELF_CONTAINED(FLTYPE, FLSIZE) \
	FUNCTION_DEFINE_FLATTEN_STRUCT_ARRAY_SELF_CONTAINED(FLTYPE, FLSIZE)

#define FUNCTION_DECLARE_FLATTEN_STRUCT_ARRAY_ITER_SELF_CONTAINED(FLTYPE, FLSIZE) \
	FUNCTION_DECLARE_FLATTEN_STRUCT_ARRAY_SELF_CONTAINED(FLTYPE, FLSIZE)

#define FUNCTION_DEFINE_FLATTEN_STRUCT_TYPE_ARRAY_ITER_SELF_CONTAINED(FLTYPE, FLSIZE) \
	FUNCTION_DEFINE_FLATTEN_STRUCT_TYPE_ARRAY_SELF_CONTAINED(FLTYPE, FLSIZE)

#define FUNCTION_DECLARE_FLATTEN_STRUCT_TYPE_ARRAY_ITER_SELF_CONTAINED(FLTYPE, FLSIZE) \
	FUNCTION_DECLARE_FLATTEN_STRUCT_TYPE_ARRAY_SELF_CONTAINED(FLTYPE, FLSIZE)

#define FUNCTION_DEFINE_FLATTEN_STRUCT_ARRAY_ITER_SELF_CONTAINED_SPECIALIZE(TAG, FLTYPE, FLSIZE) \
	FUNCTION_DEFINE_FLATTEN_STRUCT_ARRAY_SELF_CONTAINED_SPECIALIZE(TAG, FLTYPE, FLSIZE)

#define FUNCTION_DECLARE_FLATTEN_STRUCT_ARRAY_ITER_SELF_CONTAINED_SPECIALIZE(TAG, FLTYPE, FLSIZE) \
	FUNCTION_DECLARE_FLATTEN_STRUCT_ARRAY_SELF_CONTAINED_SPECIALIZE(TAG, FLTYPE, FLSIZE)

#define FUNCTION_DEFINE_FLATTEN_UNION_ARRAY_ITER(FLTYPE) \
	FUNCTION_DEFINE_FLATTEN_UNION_ARRAY(FLTYPE)
#define FUNCTION_DECLARE_FLATTEN_UNION_ARRAY_ITER(FLTYPE) \
	FUNCTION_DECLARE_FLATTEN_UNION_ARRAY(FLTYPE)

#define FUNCTION_DEFINE_FLATTEN_UNION_ARRAY_ITER_SELF_CONTAINED(FLTYPE, FLSIZE) \
	FUNCTION_DEFINE_FLATTEN_UNION_ARRAY_SELF_CONTAINED(FLTYPE, FLSIZE)

#define FUNCTION_DECLARE_FLATTEN_UNION_ARRAY_ITER_SELF_CONTAINED(FLTYPE, FLSIZE) \
	FUNCTION_DECLARE_FLATTEN_UNION_ARRAY_SELF_CONTAINED(FLTYPE, FLSIZE)

#define FUNCTION_DEFINE_FLATTEN_STRUCT_ITER(FLTYPE, ...) \
	FUNCTION_DEFINE_FLATTEN_STRUCT(FLTYPE, __VA_ARGS__)
#define FUNCTION_DECLARE_FLATTEN_STRUCT_ITER(FLTYPE) \
	FUNCTION_DECLARE_FLATTEN_STRUCT(FLTYPE)

#define FUNCTION_DEFINE_FLATTEN_STRUCT_ITER_SELF_CONTAINED(FLTYPE, FLSIZE, ...) \
	FUNCTION_DEFINE_FLATTEN_STRUCT_SELF_CONTAINED(FLTYPE, FLSIZE, __VA_ARGS__)

#define FUNCTION_DEFINE_FLATTEN_STRUCT_TYPE_ITER(FLTYPE, ...) \
	FUNCTION_DEFINE_FLATTEN_STRUCT_TYPE(FLTYPE, __VA_ARGS__)

#define FUNCTION_DECLARE_FLATTEN_STRUCT_TYPE_ITER(FLTYPE) \
	FUNCTION_DECLARE_FLATTEN_STRUCT_TYPE(FLTYPE)

#define FUNCTION_DEFINE_FLATTEN_STRUCT_TYPE_ITER_SELF_CONTAINED(FLTYPE, FLSIZE, ...) \
	FUNCTION_DEFINE_FLATTEN_STRUCT_TYPE_SELF_CONTAINED(FLTYPE, FLSIZE, __VA_ARGS__)

#define FUNCTION_DEFINE_FLATTEN_UNION_ITER(FLTYPE, ...) \
	FUNCTION_DEFINE_FLATTEN_UNION(FLTYPE, __VA_ARGS__)

#define FUNCTION_DECLARE_FLATTEN_UNION_ITER(FLTYPE) \
	FUNCTION_DECLARE_FLATTEN_UNION(FLTYPE)

#define FUNCTION_DEFINE_FLATTEN_STRUCT_ITER_SELF_CONTAINED_SPECIALIZE(TAG, FLTYPE, FLSIZE, ...) \
	FUNCTION_DEFINE_FLATTEN_STRUCT_SELF_CONTAINED_SPECIALIZE(TAG, FLTYPE, FLSIZE, __VA_ARGS__)

#define FUNCTION_DEFINE_FLATTEN_UNION_ITER_SELF_CONTAINED(FLTYPE, FLSIZE, ...) \
	FUNCTION_DEFINE_FLATTEN_UNION_SELF_CONTAINED(FLTYPE, FLSIZE, __VA_ARGS__)

/***************************
 * FLATTEN_*_ITER wrappers
 ***************************/
#define FLATTEN_STRUCT_ITER(T, p) FLATTEN_STRUCT(T, p)
#define FLATTEN_STRUCT_TYPE_ITER(T, p) FLATTEN_STRUCT_TYPE(T, p)
#define FLATTEN_STRUCT_ITER_SELF_CONTAINED(T, N, p) FLATTEN_STRUCT_SELF_CONTAINED(T, N, p)
#define FLATTEN_STRUCT_TYPE_ITER_SELF_CONTAINED(T, N, p) FLATTEN_STRUCT_TYPE_SELF_CONTAINED(T, N, p)
#define FLATTEN_STRUCT_ARRAY_ITER(T, p, n) FLATTEN_STRUCT_ARRAY(T, p, n)
#define FLATTEN_STRUCT_TYPE_ARRAY_ITER(T, p, n) FLATTEN_STRUCT_TYPE_ARRAY(T, p, n)
#define FLATTEN_STRUCT_ARRAY_ITER_SPECIALIZE(TAG, T, p, n) FLATTEN_STRUCT_ARRAY_SPECIALIZE(TAG, T, p, n)
#define FLATTEN_STRUCT_ARRAY_ITER_SELF_CONTAINED(T, N, p, n) FLATTEN_STRUCT_ARRAY_SELF_CONTAINED(T, N, p, n)
#define FLATTEN_UNION_ARRAY_ITER_SELF_CONTAINED(T, N, p, n) FLATTEN_UNION_ARRAY_SELF_CONTAINED(T, N, p, n)
#define FLATTEN_STRUCT_TYPE_ARRAY_ITER_SELF_CONTAINED(T, N, p, n) FLATTEN_STRUCT_TYPE_ARRAY_SELF_CONTAINED(T, N, p, n)

/***************************
 * AGGREGATE_*_ITER wrappers
 ***************************/
#define AGGREGATE_FLATTEN_STRUCT_ITER(T, f) AGGREGATE_FLATTEN_STRUCT(T, f)
#define AGGREGATE_FLATTEN_STRUCT_TYPE_ITER(T, f) AGGREGATE_FLATTEN_STRUCT_TYPE(T, f)
#define AGGREGATE_FLATTEN_STRUCT_STORAGE_ITER(T, p) AGGREGATE_FLATTEN_STRUCT_STORAGE(T, p)
#define AGGREGATE_FLATTEN_STRUCT_TYPE_STORAGE_ITER(T, p) AGGREGATE_FLATTEN_STRUCT_TYPE_STORAGE(T, p)
#define AGGREGATE_FLATTEN_UNION_STORAGE_ITER(T, p) AGGREGATE_FLATTEN_UNION_STORAGE(T, p)

#define AGGREGATE_FLATTEN_STRUCT_MIXED_POINTER_ITER(T, f, pre_f, post_f) AGGREGATE_FLATTEN_STRUCT_MIXED_POINTER(T, f, pre_f, post_f)
#define AGGREGATE_FLATTEN_STRUCT_TYPE_MIXED_POINTER_ITER(T, f, pre_f, post_f) AGGREGATE_FLATTEN_STRUCT_TYPE_MIXED_POINTER(T, f, pre_f, post_f)

#define AGGREGATE_FLATTEN_STRUCT_ARRAY_ITER(T, f, n) AGGREGATE_FLATTEN_STRUCT_ARRAY(T, f, n)
#define AGGREGATE_FLATTEN_STRUCT_TYPE_ARRAY_ITER(T, f, n) AGGREGATE_FLATTEN_STRUCT_TYPE_ARRAY(T, f, n)

#define AGGREGATE_FLATTEN_STRUCT_ITER_SELF_CONTAINED(T, N, f, _off) AGGREGATE_FLATTEN_STRUCT_SELF_CONTAINED(T, N, f, _off)
#define AGGREGATE_FLATTEN_STRUCT_TYPE_ITER_SELF_CONTAINED(T, N, f, _off) AGGREGATE_FLATTEN_STRUCT_TYPE_SELF_CONTAINED(T, N, f, _off)
#define AGGREGATE_FLATTEN_STRUCT_MIXED_POINTER_ITER_SELF_CONTAINED(T, N, f, _off, pre_f, post_f) AGGREGATE_FLATTEN_STRUCT_MIXED_POINTER_SELF_CONTAINED(T, N, f, _off, pre_f, post_f)
#define AGGREGATE_FLATTEN_STRUCT_TYPE_MIXED_POINTER_ITER_SELF_CONTAINED(T, N, f, _off, pre_f, post_f) AGGREGATE_FLATTEN_STRUCT_TYPE_MIXED_POINTER_SELF_CONTAINED(T, N, f, _off, pre_f, post_f)

#define AGGREGATE_FLATTEN_STRUCT_ARRAY_ITER_SELF_CONTAINED(T, N, f, _off, n) \
	AGGREGATE_FLATTEN_STRUCT_ARRAY_SELF_CONTAINED(T, N, f, _off, n)
#define AGGREGATE_FLATTEN_STRUCT_TYPE_ARRAY_ITER_SELF_CONTAINED(T, N, f, _off, n) \
	AGGREGATE_FLATTEN_STRUCT_TYPE_ARRAY_SELF_CONTAINED(T, N, f, _off, n)
#define AGGREGATE_FLATTEN_STRUCT_ARRAY_ITER_SELF_CONTAINED_SHIFTED(T, N, f, _off, n, _shift) \
	AGGREGATE_FLATTEN_STRUCT_ARRAY_SELF_CONTAINED_SHIFTED(T, N, f, _off, n, _shift)
#define AGGREGATE_FLATTEN_STRUCT_MIXED_POINTER_ARRAY_ITER_SELF_CONTAINED(T, N, f, _off, pre_f, post_f, n) \
	AGGREGATE_FLATTEN_STRUCT_MIXED_POINTER_ARRAY_SELF_CONTAINED(T, N, f, _off, pre_f, post_f, n)
#define AGGREGATE_FLATTEN_STRUCT_MIXED_POINTER_ARRAY_ITER_SELF_CONTAINED_SHIFTED(T, N, f, _off, pre_f, post_f, n, _shift) \
	AGGREGATE_FLATTEN_STRUCT_MIXED_POINTER_ARRAY_SELF_CONTAINED_SHIFTED(T, N, f, _off, pre_f, post_f, n, _shift)
#define AGGREGATE_FLATTEN_UNION_ARRAY_ITER_SELF_CONTAINED(T, N, f, _off, n) \
	AGGREGATE_FLATTEN_UNION_ARRAY_SELF_CONTAINED(T, N, f, _off, n)
#define AGGREGATE_FLATTEN_UNION_ARRAY_ITER_SELF_CONTAINED_SHIFTED(T, N, f, _off, n, _shift) \
	AGGREGATE_FLATTEN_UNION_ARRAY_SELF_CONTAINED_SHIFTED(T, N, f, _off, n, _shift)
#define AGGREGATE_FLATTEN_STRUCT_TYPE_ARRAY_ITER_SELF_CONTAINED_SHIFTED(T, N, f, _off, n, _shift) \
	AGGREGATE_FLATTEN_STRUCT_TYPE_ARRAY_SELF_CONTAINED_SHIFTED(T, N, f, _off, n, _shift)

/***************************
 * UTILITIES wrappers
 ***************************/
#define UNDER_ITER_HARNESS(...) __VA_ARGS__
